---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bind-hostpath-volume
  labels:
    type: local
spec:
  storageClassName: named-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/opt/kubernetes-storage/bind"
