---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-hostpath-volumeclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
