---
apiVersion: v1
kind: Service
metadata:
  name: bind-service-statefulset
  labels:
    app: bind-service-statefulset
spec:
  ports:
    - port: 53
      name: dns-server-tcp
      protocol: TCP
    - port: 53
      name: dns-server-udp
      protocol: UDP
  selector:
    app: bind-statefulset
