---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    stream-snippets: |
      upstream bind-statefulset-udp {
          server bind-service-statefulset.default.svc.cluster.local:53;
      }
      server {
          listen 53 udp;
          proxy_pass bind-statefulset-udp;
          proxy_responses 1;
      }
      upstream bind-statefulset-tcp {
          server bind-service-statefulset.default.svc.cluster.local:53;
      }
      server {
          listen 53;
          proxy_pass bind-statefulset-tcp;
      } 
