---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bind-ingress-statefulset
spec:
  rules:
    - http:
        paths:
          - backend:
            serviceName: bind-service-statefulset
            servicePort: 53
